spring.datasource.url=jdbc:mysql://localhost:3306/eventopia_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=@Estinfas1996
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.root=WARN
logging.level.com.eventopia=INFO
logging.file.name=/var/log/eventopia/application.log

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

server.tomcat.max-connections=10000
server.tomcat.max-threads=200
server.tomcat.min-spare-threads=10